### ISSUE TITLE
"More repos" button doesn't reset on user change

### ISSUE THREAD

**Issue by fire-eggs** [rawho/github-stats#1]
Very neat!

Buglet:
1. View github user A.
2. Click "more repos" to view more of their repositories.
3. Enter a new github user B.

Button still reads "less repos"; clicking it does nothing except reset to "more repos".

On switching user, should reset to "More repos".

**Comment by rawho** [comment]
Thanks for the issue😁 . Its solved now. You can check it

**Comment by fire-eggs** [comment]
Great!
